name: LDP
channels:
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - ipython
  - pip
  - tensorflow-gpu[version='>=1.15,<2.0']
  - tensorflow-hub
  - numpy
  - pillow
  - pydensecrf
  - nomkl
  - scikit-learn
  - cairocffi
  - matplotlib
  - opencv
